/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-21 04:45:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class get_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/board/../includes/footer.jsp", Long.valueOf(1707963034260L));
    _jspx_dependants.put("/WEB-INF/views/board/../includes/header.jsp", Long.valueOf(1707963118403L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1707367718711L));
    _jspx_dependants.put("jar:file:/C:/git_kdigital/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EX03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/git_kdigital/spring_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/EX03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>SB Admin 2 - Bootstrap Admin Theme</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- MetisMenu CSS -->\r\n");
      out.write("    <link href=\"/resources/vendor/metisMenu/metisMenu.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- DataTables CSS -->\r\n");
      out.write("    <link href=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- DataTables Responsive CSS -->\r\n");
      out.write("    <link href=\"/resources/vendor/datatables-responsive/dataTables.responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Fonts -->\r\n");
      out.write("    <link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index.html\">SB Admin v2.0</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-envelope fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-messages\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>John Smith</strong>\r\n");
      out.write("                                    <span class=\"pull-right text-muted\">\r\n");
      out.write("                                        <em>Yesterday</em>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>John Smith</strong>\r\n");
      out.write("                                    <span class=\"pull-right text-muted\">\r\n");
      out.write("                                        <em>Yesterday</em>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>John Smith</strong>\r\n");
      out.write("                                    <span class=\"pull-right text-muted\">\r\n");
      out.write("                                        <em>Yesterday</em>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                                <strong>Read All Messages</strong>\r\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-messages -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-tasks fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-tasks\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 1</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">40% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%\">\r\n");
      out.write("                                            <span class=\"sr-only\">40% Complete (success)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 2</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">20% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%\">\r\n");
      out.write("                                            <span class=\"sr-only\">20% Complete</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 3</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">60% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\">\r\n");
      out.write("                                            <span class=\"sr-only\">60% Complete (warning)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <strong>Task 4</strong>\r\n");
      out.write("                                        <span class=\"pull-right text-muted\">80% Complete</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <div class=\"progress progress-striped active\">\r\n");
      out.write("                                        <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\">\r\n");
      out.write("                                            <span class=\"sr-only\">80% Complete (danger)</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                                <strong>See All Tasks</strong>\r\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-tasks -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-bell fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-alerts\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-comment fa-fw\"></i> New Comment\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-twitter fa-fw\"></i> 3 New Followers\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">12 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-envelope fa-fw\"></i> Message Sent\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-tasks fa-fw\"></i> New Task\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <i class=\"fa fa-upload fa-fw\"></i> Server Rebooted\r\n");
      out.write("                                    <span class=\"pull-right text-muted small\">4 minutes ago</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a class=\"text-center\" href=\"#\">\r\n");
      out.write("                                <strong>See All Alerts</strong>\r\n");
      out.write("                                <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-alerts -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-user fa-fw\"></i> User Profile</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-gear fa-fw\"></i> Settings</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"login.html\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- /.navbar-top-links -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                        <li class=\"sidebar-search\">\r\n");
      out.write("                            <div class=\"input-group custom-search-form\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("                                <span class=\"input-group-btn\">\r\n");
      out.write("                                <button class=\"btn btn-default\" type=\"button\">\r\n");
      out.write("                                    <i class=\"fa fa-search\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /input-group -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"index.html\"><i class=\"fa fa-dashboard fa-fw\"></i> Dashboard</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-bar-chart-o fa-fw\"></i> Charts<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"flot.html\">Flot Charts</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"morris.html\">Morris.js Charts</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"tables.html\"><i class=\"fa fa-table fa-fw\"></i> Tables</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"forms.html\"><i class=\"fa fa-edit fa-fw\"></i> Forms</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-wrench fa-fw\"></i> UI Elements<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"panels-wells.html\">Panels and Wells</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"buttons.html\">Buttons</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"notifications.html\">Notifications</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"typography.html\">Typography</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"icons.html\"> Icons</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"grid.html\">Grid</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-sitemap fa-fw\"></i> Multi-Level Dropdown<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Second Level Item</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Second Level Item</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">Third Level <span class=\"fa arrow\"></span></a>\r\n");
      out.write("                                    <ul class=\"nav nav-third-level\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">Third Level Item</a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <!-- /.nav-third-level -->\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-files-o fa-fw\"></i> Sample Pages<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"blank.html\">Blank Page</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"login.html\">Login Page</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.sidebar-collapse -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-static-side -->\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"page-wrapper\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>");
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("		.btn-primary{background:orange;border:orange !important;}\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-12\">\r\n");
      out.write("            <h1 class=\"page-header\">Board</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.col-lg-12 -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("         <div class=\"col-lg-12\">\r\n");
      out.write("             <div class=\"panel panel-default\">\r\n");
      out.write("                 <div class=\"panel-heading\">\r\n");
      out.write("                     Read\r\n");
      out.write("                 </div>\r\n");
      out.write("                 <!-- /.panel-heading -->\r\n");
      out.write("                 <div class=\"panel-body\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    	<lable>no</lable>\r\n");
      out.write("                    	<input class=\"form-control\" name=\"bno\" value='");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("' readonly>\r\n");
      out.write("                    </div> \r\n");
      out.write("                   	<div class=\"form-group\">\r\n");
      out.write("                   		<label>Title</label>\r\n");
      out.write("                   		<input class=\"form-control\" name=\"title\" value='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("' readonly>\r\n");
      out.write("                   	</div>\r\n");
      out.write("                   	<div class=\"form-group\">\r\n");
      out.write("                   		<label>Content</label>\r\n");
      out.write("                   		<textarea class=\"form-control\" rows=\"10\" name=\"content\" readonly>");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("</textarea>\r\n");
      out.write("                   	</div>\r\n");
      out.write("                   	<div class=\"form-group\">\r\n");
      out.write("                   		<label>Writer</label>\r\n");
      out.write("                   		<input class=\"form-control\" name=\"writer\" value='");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("' readonly>\r\n");
      out.write("                   	</div>\r\n");
      out.write("                   	<button data-oper=\"modify\" class=\"btn btn-default btn-primary\">Modify</button>\r\n");
      out.write("                   	<button data-oper=\"list\" class=\"btn btn-default btn-primary\">List</button>\r\n");
      out.write("                   	\r\n");
      out.write("                   	<form id=\"operForm\" action=\"/board/modify\" method=\"get\">\r\n");
      out.write("                   		<input type=\"hidden\" id=\"bno\" name=\"bno\" value='");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("                   		<input type=\"hidden\" id=\"pageNum\" name=\"pageNum\" value='");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("                   		<input type=\"hidden\" id=\"amount\" name=\"amount\" value='");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("                   		<input type=\"hidden\" id=\"keyword\" name=\"keyword\" value='");
      if (_jspx_meth_c_005fout_005f7(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("                   		<input type=\"hidden\" id=\"type\" name=\"type\" value='");
      if (_jspx_meth_c_005fout_005f8(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("                   	</form>\r\n");
      out.write("                    \r\n");
      out.write("                 </div>\r\n");
      out.write("                 <!-- /.panel-body -->\r\n");
      out.write("             </div>\r\n");
      out.write("             <!-- /.panel -->\r\n");
      out.write("         </div>\r\n");
      out.write("         <!-- /.col-lg-12 -->\r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("    <!-- 댓글 목록 -----------------------------------------------------------------------------------------------> \r\n");
      out.write("     <div class=\"row\">\r\n");
      out.write("     	<div class=\"col-lg-12\">\r\n");
      out.write("     		<div class=\"panel panel-default\">\r\n");
      out.write("     			<div class=\"panel-heading\">\r\n");
      out.write("     				<i class=\"fa fa-comments f-fw\"></i> Reply\r\n");
      out.write("     				<button id=\"addReplyBtn\" class=\"btn btn-primary btn-xs pull-right\">New Reply</button>\r\n");
      out.write("     			</div>\r\n");
      out.write("     			<div class=\"panel-body\">\r\n");
      out.write("     				<ul class=\"chat\">\r\n");
      out.write("     				\r\n");
      out.write("     				</ul>\r\n");
      out.write("     			</div>\r\n");
      out.write("     			<div class=\"panel-footer\" style=\"height:50px;\"></div>     			\r\n");
      out.write("     		</div>\r\n");
      out.write("     	</div>\r\n");
      out.write("     </div>\r\n");
      out.write("     <!-- 댓글 목록.end --> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 댓글 등록 modal ----------------------------------------------------------------------------------------->    \r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("                aria-hidden=\"true\">&times;</button>\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"myModalLabel\">REPLY MODAL</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label>Reply</label> \r\n");
      out.write("                <input class=\"form-control\" name='reply' value='New Reply!!!!'>\r\n");
      out.write("              </div>      \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label>Replyer</label> \r\n");
      out.write("                <input class=\"form-control\" name='replyer' value='replyer' readonly>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label>Reply Date</label> \r\n");
      out.write("                <input class=\"form-control\" name='replyDate' value='2018-01-01 13:13'>\r\n");
      out.write("              </div>\r\n");
      out.write("      \r\n");
      out.write("            </div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("	        <button id='modalModBtn' type=\"button\" class=\"btn btn-warning\">Modify</button>\r\n");
      out.write("	        <button id='modalRemoveBtn' type=\"button\" class=\"btn btn-danger\">Remove</button>\r\n");
      out.write("	        <button id='modalRegisterBtn' type=\"button\" class=\"btn btn-primary\">Register</button>\r\n");
      out.write("	        <button id='modalCloseBtn' type=\"button\" class=\"btn btn-default\">Close</button>\r\n");
      out.write("	      </div>          \r\n");
      out.write("      	  </div>\r\n");
      out.write("          <!-- /.modal-content -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.modal-dialog -->\r\n");
      out.write("    </div>\r\n");
      out.write("	<!-- 댓글 등록 modal.end -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/reply.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    	function showList(page){\r\n");
      out.write("    		var bnoValue='");
      if (_jspx_meth_c_005fout_005f9(_jspx_page_context))
        return;
      out.write("'; //부모글 번호\r\n");
      out.write("    		replyService.getList({bno:bnoValue,page:page||1},function(replyCnt,list){\r\n");
      out.write("    			console.log(\"replyCnt : \"+replyCnt);\r\n");
      out.write("    			console.log(\"page : \"+page);\r\n");
      out.write("    			//page가 -1이면 마지막 페이지로 이동\r\n");
      out.write("    			if(pageNum==-1){\r\n");
      out.write("    				pageNum=Math.ceil(replyCnt/10.0);\r\n");
      out.write("    				showList(pageNum);\r\n");
      out.write("    				return;\r\n");
      out.write("    			}\r\n");
      out.write("    			var str=\"\";\r\n");
      out.write("    			// list가 null이거나, list.length가 0이면.. 즉 댓글목록이 없으면 중지\r\n");
      out.write("    			if(list==null || list.length==0){\r\n");
      out.write("    				return;\r\n");
      out.write("    			}\r\n");
      out.write("    			for(var i=0,len=list.length || 0;i<len;i++){\r\n");
      out.write("    				str+=\"<li class='left clearfix' data-rno='\"+list[i].rno+\"' style='cursor:pointer'>\";\r\n");
      out.write("    				str+=\"<div><div class='header'><strong class='primary-font'>[\"+list[i].rno+\"] \"+list[i].replyer+\"</strong>\";\r\n");
      out.write("    				str+=\" <small class='pull-right text-muted'>\"+replyService.displayTime(list[i].replyDate)+\"</small></div>\";\r\n");
      out.write("    				str+=\" <p>\"+list[i].reply+\"</p></div></li>\"  \r\n");
      out.write("    			}\r\n");
      out.write("    			$(\".chat\").html(str);\r\n");
      out.write("				showReplyPage(replyCnt,page);\r\n");
      out.write("    		});    		\r\n");
      out.write("    	}\r\n");
      out.write("    	\r\n");
      out.write("    	function showReplyPage(replyCnt,pageNum){	\r\n");
      out.write("    		console.log(\"replyCnt ...... \"+replyCnt);\r\n");
      out.write("    		\r\n");
      out.write("    		var endNum=Math.ceil(pageNum/10.0)*10; // 끝번호. 즉, 1,2,3....10 에서 10\r\n");
      out.write("    		var startNum=endNum-9; // 시작번호\r\n");
      out.write("    		var prev=startNum!=1; //previous유무\r\n");
      out.write("    		var next=false; // ext 유무. 기본값은 false. 즉, 안보임\r\n");
      out.write("    		// 댓글갯수가 endNum*10보다 작을 때(실제끝페이지가 계산으로 구한 마지막페이지보다 작을 때)\r\n");
      out.write("    		if(endNum*10>=replyCnt){\r\n");
      out.write("    			endNum=Math.ceil(replyCnt/10.0);//마지막페이지 변경\r\n");
      out.write("    		}\r\n");
      out.write("    		// 댓글갯수가 endNum*10보다 크면 next존재\r\n");
      out.write("    		if(endNum*10<replyCnt){\r\n");
      out.write("    			next=true;\r\n");
      out.write("    		}\r\n");
      out.write("    		var str=\"<ul class='pagination pull-right' style='margin:0 !important'>\";\r\n");
      out.write("    		if(prev){\r\n");
      out.write("    			str+=\"<li class='page-item'><a class='page-link' href='\"+(startNum-1)+\"'>Previous</a></li>\";\r\n");
      out.write("    		}\r\n");
      out.write("    		for(var i=startNum;i<=endNum;i++){\r\n");
      out.write("    			var active=pageNum==i?\"active\":\"\"; // 페이지번호가 현재페이지이면? active실행. 아니라면 빈칸(즉, 아무것도 실행안함)\r\n");
      out.write("    			str+=\"<li class='page-item \"+active+\"'><a class='page-link' href='\"+i+\"'>\"+i+\"</a></li>\";\r\n");
      out.write("    		}\r\n");
      out.write("    		if(next){\r\n");
      out.write("    			str+=\"<li class='page-item'><a class='page-link' href='\"+(endNum+1)+\"'>Next</a></li>\";\r\n");
      out.write("    		}\r\n");
      out.write("    		str+=\" </ul>\";\r\n");
      out.write("    		$(\".panel-footer\").html(str);\r\n");
      out.write("    	}\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("    	$(document).ready(function(){\r\n");
      out.write("    		/* 필요한 변수. 찾을 태그를 먼저 작성 **************************************************/\r\n");
      out.write("    		var bnoValue='");
      if (_jspx_meth_c_005fout_005f10(_jspx_page_context))
        return;
      out.write("'; //부모글 번호\r\n");
      out.write("    		var replyUL=$(\".chat\"); // 댓글목록 ul\r\n");
      out.write("    		\r\n");
      out.write("    		var modal = $(\".modal\"); // 모달창\r\n");
      out.write("    	    var modalInputReply = modal.find(\"input[name='reply']\"); //댓글내용\r\n");
      out.write("    	    var modalInputReplyer = modal.find(\"input[name='replyer']\"); //댓글작성자\r\n");
      out.write("    	    var modalInputReplyDate = modal.find(\"input[name='replyDate']\"); //댓글작성일    	    \r\n");
      out.write("    	    var modalModBtn = $(\"#modalModBtn\"); //수정버튼\r\n");
      out.write("    	    var modalRemoveBtn = $(\"#modalRemoveBtn\"); //삭제버튼\r\n");
      out.write("    	    var modalRegisterBtn = $(\"#modalRegisterBtn\"); //등록버튼    		\r\n");
      out.write("    		\r\n");
      out.write("    		var operForm=$(\"#operForm\"); // modify, list버튼 처리 폼\r\n");
      out.write("    		\r\n");
      out.write("    	    var pageNum = 1; // 페이지번호 기본값\r\n");
      out.write("    	    var replyPageFooter = $(\".panel-footer\"); // 댓글페이징처리 번호가 출력되는 부분    \r\n");
      out.write("    	    \r\n");
      out.write("    	    \r\n");
      out.write("    	    showList(pageNum); //댓글목록 출력\r\n");
      out.write("    	    \r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		/*modify 버튼 이벤트처리 ************************************/\r\n");
      out.write("    		$(\"button[data-oper='modify']\").on(\"click\",function(){\r\n");
      out.write("    			operForm.attr(\"action\",\"/board/modify\").submit();\r\n");
      out.write("    		});\r\n");
      out.write("    		/*event 버튼 이벤트처리***********************************/\r\n");
      out.write("    		$(\"button[data-oper='list']\").on(\"click\",function(){\r\n");
      out.write("    			//$(\"#bno\").remove();\r\n");
      out.write("    			operForm.attr(\"action\",\"/board/list\").submit();\r\n");
      out.write("    		});\r\n");
      out.write("    		/*댓글등록 버튼 이벤트처리**********************************/\r\n");
      out.write("    		$(\"#addReplyBtn\").on(\"click\",function(e){\r\n");
      out.write("    			modal.find(\"input\").val(\"\"); // input 태그 초기화. 초기화 이유는 모달창 하나로 수정할때도, 등록할때도 쓰기 때문에.\r\n");
      out.write("    			modalInputReplyDate.closest(\"div\").hide(); // 댓글작성일 안보이게.\r\n");
      out.write("    			modal.find(\"button[id!='modalCloseBtn']\").hide(); // close버튼만 남고 나머지 버튼들 안보이게\r\n");
      out.write("    			modalRegisterBtn.show(); //등록버튼만 다시 보이게.\r\n");
      out.write("    			modal.modal(\"show\"); // modal창 띄우기.\r\n");
      out.write("    		});\r\n");
      out.write("    		/*모달창 close버튼 이벤트처리**********************************/\r\n");
      out.write("    		$(\"#modalCloseBtn\").on(\"click\",function(){\r\n");
      out.write("    			modal.modal(\"hide\");\r\n");
      out.write("    		});\r\n");
      out.write("    		/*모달창 댓글등록버튼 이벤트처리**********************************/\r\n");
      out.write("    		modalRegisterBtn.on(\"click\",function(){\r\n");
      out.write("    			//서버에 전송할 데이터\r\n");
      out.write("    			var reply={\r\n");
      out.write("   					reply:modalInputReply.val(),\r\n");
      out.write("   					replyer:modalInputReplyer.val(),\r\n");
      out.write("   					bno:bnoValue\r\n");
      out.write("    			};\r\n");
      out.write("    			//댓글등록 함수 호출\r\n");
      out.write("    			//아래에서 에러는 표시를 안하고 있는데.. 만약 할려면reply,function(result),function(error)로 파라미터 만들어서 진행해야함.\r\n");
      out.write("    			replyService.add(reply,function(result){\r\n");
      out.write("    				alert(result); // controller에서 전달된 'success' 출력\r\n");
      out.write("    				modal.find(\"input\").val(\"\"); // input태그 초기화\r\n");
      out.write("    				modal.modal(\"hide\"); // modal창 안보이게\r\n");
      out.write("    				\r\n");
      out.write("    				showList(1); // 댓글목록 갱신\r\n");
      out.write("    			});    			\r\n");
      out.write("    		});\r\n");
      out.write("    		\r\n");
      out.write("    		/*댓글 페이지번호 이벤트처리*************************************************/\r\n");
      out.write("    		//delegate 위임. li a 가 아직 생성되지 않아서 부모에게 event 처리 위임\r\n");
      out.write("    		//jQuery로 footer에 이벤트를 건다고 했을 때, footer가 비어있을 때는 이벤트를 걸 수 없음.\r\n");
      out.write("			//따라서 부모인 panel-footer를 가지고 이벤트를 걸어야 함. 이를 delegate 위임이라고 표현\r\n");
      out.write("			//아래 코드에서 replyPageFooter가 부모 / \"click\" 이벤트 / \"li a\" 자식\r\n");
      out.write("			//앞으로 만들 자식인 \"li a\"에 이벤트처리를 하기 위해, 부모인 replyPageFooter를 delegate처리\r\n");
      out.write("        	replyPageFooter.on(\"click\", \"li a\", function(e){\r\n");
      out.write("        		e.preventDefault(); // 클릭 시 다음 페이지 이동 방지\r\n");
      out.write("        		var targetPageNum = $(this).attr(\"href\");\r\n");
      out.write("        		pageNum=targetPageNum;\r\n");
      out.write("        		showList(pageNum);\r\n");
      out.write("        	});\r\n");
      out.write("    		\r\n");
      out.write("    		/*댓글 조회 클릭 이벤트 처리************************************************/\r\n");
      out.write("    		//delegate 위임. li가 아직 생성되지 않아서 부모에게 이벤트처리 위임\r\n");
      out.write("  			$(\".chat\").on(\"click\", \"li\", function(e){\r\n");
      out.write("    			// hidden태그는 값이 하나일때 주로 사용. 지금처럼 목록을 불러올 때는 jQuery의 data 메서드를 사용.\r\n");
      out.write("    			var rno = $(this).data(\"rno\");\r\n");
      out.write("    			replyService.get(rno, function(reply){\r\n");
      out.write("    				modalInputReply.val(reply.reply);\r\n");
      out.write("    				modalInputReplyer.val(reply.replyer);\r\n");
      out.write("    				// (첫번째)'readonly' 설정의 값을 'readonly'(두번째)로 설정했다는 의미\r\n");
      out.write("    				modalInputReplyDate.val(replyService.displayTime(reply.replyDate)).attr(\"readonly\",\"readonly\");\r\n");
      out.write("    				modal.data(\"rno\", reply.rno); // 댓글번호. data-rno 생성됨\r\n");
      out.write("    				\r\n");
      out.write("    				modal.find(\"button[id!='modalCloseBtn']\").hide();\r\n");
      out.write("    				modalModBtn.show();\r\n");
      out.write("    				modalRemoveBtn.show();\r\n");
      out.write("    				\r\n");
      out.write("    				$(\".modal\").modal(\"show\");\r\n");
      out.write("    			});\r\n");
      out.write("    		});\r\n");
      out.write("    		\r\n");
      out.write("    		/*댓글 수정 버튼 이벤트 처리************************************************/  \r\n");
      out.write("    		modalModBtn.on(\"click\",function(){\r\n");
      out.write("    			var reply={rno:modal.data(\"rno\"), reply:modalInputReply.val(), replyer:modalInputReplyer.val()}\r\n");
      out.write("    			replyService.update(reply, function(result){\r\n");
      out.write("    				alert(result);\r\n");
      out.write("    				modal.modal(\"hide\");\r\n");
      out.write("    				showList(pageNum);\r\n");
      out.write("    			});\r\n");
      out.write("    		});\r\n");
      out.write("\r\n");
      out.write("    		/*댓글 삭제 버튼 이벤트 처리************************************************/  \r\n");
      out.write("    		modalRemoveBtn.on(\"click\", function(){\r\n");
      out.write("    			var rno=modal.data(\"rno\");\r\n");
      out.write("    			replyService.remove(rno,function(result){\r\n");
      out.write("    				alert(result);\r\n");
      out.write("    				modal.modal(\"hide\");\r\n");
      out.write("    				showList(pageNum);    				\r\n");
      out.write("    			});\r\n");
      out.write("    		});\r\n");
      out.write("    	});\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("        <!-- /#page-wrapper -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("<!--<script src=\"/resources/vendor/jquery/jquery.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- DataTables JavaScript -->\r\n");
      out.write("    <script src=\"/resources/vendor/datatables/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/vendor/datatables-plugins/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/vendor/datatables-responsive/dataTables.responsive.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom Theme JavaScript -->\r\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page-Level Demo Scripts - Tables - Use for reference -->\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $('#dataTables-example').DataTable({\r\n");
      out.write("            responsive: true\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/board/get.jsp(29,67) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/board/get.jsp(33,69) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/board/get.jsp(37,86) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f3_reused = false;
    try {
      _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f3.setParent(null);
      // /WEB-INF/views/board/get.jsp(41,70) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
      if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      _jspx_th_c_005fout_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f4_reused = false;
    try {
      _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f4.setParent(null);
      // /WEB-INF/views/board/get.jsp(47,69) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
      if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      _jspx_th_c_005fout_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f5_reused = false;
    try {
      _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f5.setParent(null);
      // /WEB-INF/views/board/get.jsp(48,77) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.pageNum}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
      if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      _jspx_th_c_005fout_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f6_reused = false;
    try {
      _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f6.setParent(null);
      // /WEB-INF/views/board/get.jsp(49,75) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.amount}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
      if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      _jspx_th_c_005fout_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f7_reused = false;
    try {
      _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f7.setParent(null);
      // /WEB-INF/views/board/get.jsp(50,77) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.keyword}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
      if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      _jspx_th_c_005fout_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f8_reused = false;
    try {
      _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f8.setParent(null);
      // /WEB-INF/views/board/get.jsp(51,71) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.type}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
      if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      _jspx_th_c_005fout_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f9_reused = false;
    try {
      _jspx_th_c_005fout_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f9.setParent(null);
      // /WEB-INF/views/board/get.jsp(125,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f9 = _jspx_th_c_005fout_005f9.doStartTag();
      if (_jspx_th_c_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
      _jspx_th_c_005fout_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f10 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f10_reused = false;
    try {
      _jspx_th_c_005fout_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f10.setParent(null);
      // /WEB-INF/views/board/get.jsp(185,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f10.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bno}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f10 = _jspx_th_c_005fout_005f10.doStartTag();
      if (_jspx_th_c_005fout_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f10);
      _jspx_th_c_005fout_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f10_reused);
    }
    return false;
  }
}
